whi_imu:
  loop_hz: 50 # hz
  frame_id: 'imu'
  data_topic: 'imu_data'
  mag_topic: 'mag_data'
  temp_topic: 'temp_data'
  hardware_interface:
    module: 'JY61P'
    port: '/dev/imu'
    baudrate: 115200
    pack_length: 11
    # JY-61 is 0xff 0xaa 0x52; JY-61P is 0xff 0xaa 0x01 0x04 0x00 with unlock
    unlock: [0xff, 0xaa, 0x69, 0x88, 0xb5]
    reset_yaw: [0xff, 0xaa, 0x01, 0x04, 0x00]
    with_magnetic: true
    with_temperature: false
